### ISSUE TITLE
not all images have caption annotations

### ISSUE THREAD

**Issue by zhousteven** [iflytek/VLE#4]
when i run script "write_vqa.py", use the public datasets as author recommended in "README.md", console output some message as show below:
./VLE/VLE-main/examples/VQA/write_vqa.py 
100%|██████████| 443757/443757 [00:00<00:00, 851830.30it/s]
100%|██████████| 214354/214354 [00:00<00:00, 431325.80it/s]
100%|██████████| 447793/447793 [00:00<00:00, 809395.66it/s] 
100%|██████████| 107394/107394 [00:00<00:00, 3530035.22it/s]
100%|██████████| 443757/443757 [00:00<00:00, 7974002.36it/s]
100%|██████████| 214354/214354 [00:00<00:00, 7733833.17it/s]
100%|██████████| 658111/658111 [00:06<00:00, 100919.83it/s]
100%|██████████| 443757/443757 [00:01<00:00, 359162.75it/s]
100%|██████████| 214354/214354 [00:00<00:00, 237090.17it/s]
not all images have caption annotations
82783 82774 82774
100%|██████████| 82774/82774 [56:48<00:00, 24.28it/s]
not all images have caption annotations
40504 40503 40503
100%|██████████| 40503/40503 [26:37<00:00, 25.35it/s]
  0%|          | 0/81434 [00:00<?, ?it/s]all images have caption annotations
81434 81434 81434
100%|██████████| 81434/81434 [49:52<00:00, 27.21it/s]
not all images have caption annotations
81434 36807 36807
100%|██████████| 36807/36807 [19:12<00:00, 31.93it/s]

Process finished with exit code 0

some line mentioned that" not all image have caption annotations",should i care about this message? whether it effect the next training steps?
please kindly answer my doubts~
tks~

**Comment by GoGoJoestar** [comment]
The message only means some images have no annotations in this dataset. It is normal in Dataset Preparation process.
